using System.Numerics;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._Sunrise.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class LikeCounterControl : Control
{
    private const string LikeButtonAnimationKey = "like-counter-button-click";
    private const float LikeButtonPressDuration = 0.16f;
    private const float LikeButtonReleaseDuration = 0.16f;
    private const float LikeButtonPressedScale = 0.89f;
    private static readonly Color LikeButtonPressedModulate = Color.FromHex("#505050");
    private static readonly Color LikeButtonLikedColor = Color.FromHex("#E74C3C");
    private static readonly Color LikeButtonUnlikedColor = Color.White;

    private int _likeCount;
    private bool _likedByPlayer;
    private string _likeEmoji = "\u2665";
    private Vector2 _baseLikeButtonSize;

    public event Action? OnLikePressed;

    public int LikeCount
    {
        get => _likeCount;
        set
        {
            _likeCount = value;
            UpdateLikeButton();
        }
    }

    public bool LikedByPlayer
    {
        get => _likedByPlayer;
        set
        {
            _likedByPlayer = value;
            UpdateLikeButton();
        }
    }

    public string LikeEmoji
    {
        get => _likeEmoji;
        set
        {
            _likeEmoji = string.IsNullOrWhiteSpace(value) ? "\u2665" : value;
            UpdateLikeButton();
        }
    }

    public LikeCounterControl()
    {
        RobustXamlLoader.Load(this);

        var baseWidth = float.IsNaN(LikeButton.SetWidth) ? LikeButton.MinWidth : LikeButton.SetWidth;
        var baseHeight = float.IsNaN(LikeButton.SetHeight) ? LikeButton.MinHeight : LikeButton.SetHeight;
        _baseLikeButtonSize = new Vector2(baseWidth, baseHeight);

        // Allow temporary shrink animation below legacy min constraints.
        LikeButton.MinSize = Vector2.Zero;
        LikeButton.SetSize = _baseLikeButtonSize;

        LikeButton.AnimationCompleted += OnLikeButtonAnimationCompleted;
        LikeButton.OnPressed += _ =>
        {
            PlayLikeButtonClickAnimation();
            ApplyLocalLikeToggle();
            OnLikePressed?.Invoke();
        };

        LikeCount = 0;
        LikedByPlayer = false;
    }

    private void UpdateLikeButton()
    {
        LikeButton.Text = $"{LikeEmoji} {_likeCount}";
        SetLikeButtonVisual(_likedByPlayer);
    }

    private void ApplyLocalLikeToggle()
    {
        if (_likedByPlayer)
        {
            _likedByPlayer = false;
            _likeCount = Math.Max(0, _likeCount - 1);
        }
        else
        {
            _likedByPlayer = true;
            _likeCount++;
        }

        UpdateLikeButton();
    }

    private void PlayLikeButtonClickAnimation()
    {
        if (LikeButton.HasRunningAnimation(LikeButtonAnimationKey))
            LikeButton.StopAnimation(LikeButtonAnimationKey);

        LikeButton.Modulate = Color.White;
        LikeButton.SetSize = _baseLikeButtonSize;

        var animationLength = LikeButtonPressDuration + LikeButtonReleaseDuration;
        var pressedButtonSize = _baseLikeButtonSize * LikeButtonPressedScale;

        var animation = new Animation
        {
            Length = TimeSpan.FromSeconds(animationLength),
            AnimationTracks =
            {
                new AnimationTrackControlProperty
                {
                    Property = nameof(Modulate),
                    InterpolationMode = AnimationInterpolationMode.Linear,
                    KeyFrames =
                    {
                        new AnimationTrackProperty.KeyFrame(Color.White, 0f),
                        new AnimationTrackProperty.KeyFrame(LikeButtonPressedModulate, LikeButtonPressDuration),
                        new AnimationTrackProperty.KeyFrame(Color.White, LikeButtonReleaseDuration),
                    }
                },
                new AnimationTrackControlProperty
                {
                    Property = nameof(SetSize),
                    InterpolationMode = AnimationInterpolationMode.Linear,
                    KeyFrames =
                    {
                        new AnimationTrackProperty.KeyFrame(_baseLikeButtonSize, 0f),
                        new AnimationTrackProperty.KeyFrame(pressedButtonSize, LikeButtonPressDuration),
                        new AnimationTrackProperty.KeyFrame(_baseLikeButtonSize, LikeButtonReleaseDuration),
                    }
                }
            }
        };

        LikeButton.PlayAnimation(animation, LikeButtonAnimationKey);
    }

    private void OnLikeButtonAnimationCompleted(string key)
    {
        if (key != LikeButtonAnimationKey)
            return;

        LikeButton.Modulate = Color.White;
        LikeButton.SetSize = _baseLikeButtonSize;
    }

    private void SetLikeButtonVisual(bool likedByPlayer)
    {
        LikeButton.Label.FontColorOverride = likedByPlayer ? LikeButtonLikedColor : LikeButtonUnlikedColor;
    }
}
