using System;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._Sunrise.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class LikeCounterControl : Control
{
    private const string LikeButtonAnimationKey = "like-counter-button-click";
    private const float LikeButtonPressDuration = 0.16f;
    private const float LikeButtonReleaseDuration = 0.20f;
    private static readonly Color LikeButtonPressedModulate = Color.FromHex("#505050");
    private static readonly Color LikeButtonLikedColor = Color.FromHex("#E74C3C");
    private static readonly Color LikeButtonUnlikedColor = Color.White;

    private int _likeCount;
    private bool _likedByPlayer;
    private string _likeEmoji = "\u2665";

    public event Action? OnLikePressed;

    public int LikeCount
    {
        get => _likeCount;
        set
        {
            _likeCount = value;
            UpdateLikeButton();
        }
    }

    public bool LikedByPlayer
    {
        get => _likedByPlayer;
        set
        {
            _likedByPlayer = value;
            UpdateLikeButton();
        }
    }

    public string LikeEmoji
    {
        get => _likeEmoji;
        set
        {
            _likeEmoji = string.IsNullOrWhiteSpace(value) ? "\u2665" : value;
            UpdateLikeButton();
        }
    }

    public LikeCounterControl()
    {
        RobustXamlLoader.Load(this);

        LikeButton.AnimationCompleted += OnLikeButtonAnimationCompleted;
        LikeButton.OnPressed += _ =>
        {
            PlayLikeButtonClickAnimation();
            SetLikeButtonVisual(!_likedByPlayer);
            OnLikePressed?.Invoke();
        };

        LikeCount = 0;
        LikedByPlayer = false;
    }

    private void UpdateLikeButton()
    {
        LikeButton.Text = $"{LikeEmoji} {_likeCount}";
        SetLikeButtonVisual(_likedByPlayer);
    }

    private void PlayLikeButtonClickAnimation()
    {
        if (LikeButton.HasRunningAnimation(LikeButtonAnimationKey))
            LikeButton.StopAnimation(LikeButtonAnimationKey);
        if (LikeButton.Label.HasRunningAnimation(LikeButtonAnimationKey))
            LikeButton.Label.StopAnimation(LikeButtonAnimationKey);

        LikeButton.Modulate = Color.White;
        LikeButton.Label.Modulate = Color.White;

        var animationLength = LikeButtonPressDuration + LikeButtonReleaseDuration;

        var animation = new Animation
        {
            Length = TimeSpan.FromSeconds(animationLength),
            AnimationTracks =
            {
                new AnimationTrackControlProperty
                {
                    Property = nameof(Control.Modulate),
                    InterpolationMode = AnimationInterpolationMode.Linear,
                    KeyFrames =
                    {
                        new AnimationTrackProperty.KeyFrame(Color.White, 0f),
                        new AnimationTrackProperty.KeyFrame(LikeButtonPressedModulate, LikeButtonPressDuration),
                        new AnimationTrackProperty.KeyFrame(Color.White, LikeButtonReleaseDuration),
                    }
                }
            }
        };

        LikeButton.PlayAnimation(animation, LikeButtonAnimationKey);
        LikeButton.Label.PlayAnimation(animation, LikeButtonAnimationKey);
    }

    private void OnLikeButtonAnimationCompleted(string key)
    {
        if (key != LikeButtonAnimationKey)
            return;

        LikeButton.Modulate = Color.White;
        LikeButton.Label.Modulate = Color.White;
    }

    private void SetLikeButtonVisual(bool likedByPlayer)
    {
        LikeButton.Label.FontColorOverride = likedByPlayer ? LikeButtonLikedColor : LikeButtonUnlikedColor;
    }
}
