using System.Collections.Generic;
using System.Numerics;
using Content.Client._Sunrise.SponsorTiers;
using Content.Shared._Sunrise.SunriseCCVars;
using Content.Shared.CCVar;
using Content.Sunrise.Interfaces.Shared;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Utility;
using Robust.Client.AutoGenerated;

namespace Content.Client._Sunrise.Sponsor;

[GenerateTypedNameReferences]
public sealed partial class SponsorWindow : BaseWindow
{
    [Dependency] private readonly IConfigurationManager _config = default!;
    [Dependency] private readonly ISharedPlayerManager _player = default!;
    [Dependency] private readonly IUriOpener _uri = default!;
    private const int DragMarginSize = 7;
    private readonly ISharedSponsorsManager? _sponsorsManager;
    private readonly ISharedAccountBindingsManager? _accountBindingsManager;
    private readonly List<SponsorInfo> _sponsorTiers = new();
    private readonly SponsorTiersUIController _sponsorTiersController;

    private DonationTerminalTab _selectedTab = DonationTerminalTab.Main;
    private string _paymentLink = string.Empty;
    private string _accountManagementUrl = string.Empty;
    private int _currentSponsorTier;

    public SponsorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        IoCManager.Instance!.TryResolveType(out _sponsorsManager);
        IoCManager.Instance!.TryResolveType(out _accountBindingsManager);
        _sponsorTiersController = UserInterfaceManager.GetUIController<SponsorTiersUIController>();

        CloseButton.OnPressed += _ => Close();
        MainTabButton.OnPressed += _ => SelectTab(DonationTerminalTab.Main);
        ShopTabButton.OnPressed += _ => SelectTab(DonationTerminalTab.Shop);
        SubscriptionsTabButton.OnPressed += _ => SelectTab(DonationTerminalTab.Subscriptions);
        MainSubscriptionDetailsButton.OnPressed += _ => OpenSponsorTierDetails();
        MainSubscriptionPurchaseButton.OnPressed += _ => OpenPaymentLink();
        MainAccountManageButton.OnPressed += _ => OpenAccountManagementLink();
        SubscriptionPurchaseButton.OnPressed += _ => OpenPaymentLink();
        MainSubscriptionDetailsButton.TextAlign = Label.AlignMode.Center;
        MainSubscriptionPurchaseButton.TextAlign = Label.AlignMode.Center;
        MainAccountManageButton.TextAlign = Label.AlignMode.Center;
        SubscriptionPurchaseButton.TextAlign = Label.AlignMode.Center;
        PurchaseCancelButton.TextAlign = Label.AlignMode.Center;
        PurchaseConfirmButton.TextAlign = Label.AlignMode.Center;

        SelectTab(_selectedTab);

        _config.OnValueChanged(SunriseCCVars.PaymentLink, OnPaymentLinkChanged, true);
        _config.OnValueChanged(CCVars.InfoLinksAccountManagement, OnAccountManagementUrlChanged, true);

        BalanceButton.OnPressed += _ => OpenPaymentLink();
        InitializeSponsorShopUi();

        RefreshPlayerInfo();
        RefreshBindings(_accountBindingsManager?.GetSnapshot() ?? AccountBindingsSnapshot.Unavailable());

        if (_sponsorsManager != null)
        {
            _sponsorsManager.LoadedSponsorInfo += RefreshSponsorInfo;
            _sponsorsManager.LoadedSponsorTiers += RefreshSponsorTiers;
            RefreshSponsorTiers(_sponsorsManager.GetSponsorTiers());
        }
        else
        {
            SetSubscriptionText(Loc.GetString("donation-terminal-unavailable"));
        }

        if (_accountBindingsManager != null)
        {
            _accountBindingsManager.BindingsChanged += OnBindingsChanged;
            _accountBindingsManager.RequestBindingsRefresh();
        }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _config.UnsubValueChanged(SunriseCCVars.PaymentLink, OnPaymentLinkChanged);
            _config.UnsubValueChanged(CCVars.InfoLinksAccountManagement, OnAccountManagementUrlChanged);

            if (_sponsorsManager != null)
            {
                _sponsorsManager.LoadedSponsorInfo -= RefreshSponsorInfo;
                _sponsorsManager.LoadedSponsorTiers -= RefreshSponsorTiers;
            }

            if (_accountBindingsManager != null)
                _accountBindingsManager.BindingsChanged -= OnBindingsChanged;

            DisposeSponsorShopUi();
        }

        base.Dispose(disposing);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.Move;

        if (Resizable)
        {
            if (relativeMousePos.Y < DragMarginSize)
            {
                mode = DragMode.Top;
            }
            else if (relativeMousePos.Y > Size.Y - DragMarginSize)
            {
                mode = DragMode.Bottom;
            }

            if (relativeMousePos.X < DragMarginSize)
            {
                mode |= DragMode.Left;
            }
            else if (relativeMousePos.X > Size.X - DragMarginSize)
            {
                mode |= DragMode.Right;
            }
        }

        return mode;
    }

    private enum DonationTerminalTab : byte
    {
        Main,
        Shop,
        Subscriptions
    }
}
