using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.Ghost.UI;
using Content.Shared._Sunrise.SunriseCCVars;
using Content.Sunrise.Interfaces.Client;
using Content.Sunrise.Interfaces.Shared;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Utility;
using Robust.Client.AutoGenerated;
using Content.Client._Sunrise.Sheetlets;

namespace Content.Client._Sunrise.Sponsor;

[GenerateTypedNameReferences]
public sealed partial class SponsorWindow : BaseWindow
{
    [Dependency] private readonly IConfigurationManager _config = default!;
    [Dependency] private readonly ISharedPlayerManager _player = default!;
    [Dependency] private readonly IUriOpener _uri = default!;
    private const int DragMarginSize = 7;
    private readonly ISharedSponsorsManager? _sponsorsManager;
    private readonly List<SponsorInfo> _sponsorTiers = new();

    private DonationTerminalTab _selectedTab = DonationTerminalTab.Main;
    private string _paymentLink = string.Empty;

    public SponsorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        IoCManager.Instance!.TryResolveType(out _sponsorsManager);

        CloseButton.OnPressed += _ => Close();
        MainTabButton.OnPressed += _ => SelectTab(DonationTerminalTab.Main);
        ShopTabButton.OnPressed += _ => SelectTab(DonationTerminalTab.Shop);
        SubscriptionsTabButton.OnPressed += _ => SelectTab(DonationTerminalTab.Subscriptions);
        InventoryTabButton.OnPressed += _ => SelectTab(DonationTerminalTab.Inventory);

        SelectTab(_selectedTab);

        _config.OnValueChanged(SunriseCCVars.PaymentLink, OnPaymentLinkChanged, true);

        BalanceButton.OnPressed += _ => OpenPaymentLink();

        RefreshPlayerInfo();

        if (_sponsorsManager != null)
        {
            _sponsorsManager.LoadedSponsorInfo += RefreshSponsorInfo;
            _sponsorsManager.LoadedSponsorTiers += RefreshSponsorTiers;
            RefreshSponsorTiers(_sponsorsManager.GetSponsorTiers());
        }
        else
        {
            SetSubscriptionText(Loc.GetString("donation-terminal-unavailable"));
        }
    }

    private void OnPaymentLinkChanged(string url)
    {
        _paymentLink = url;
        BalanceButton.Disabled = string.IsNullOrEmpty(url);
    }

    private void OpenPaymentLink()
    {
        if (string.IsNullOrEmpty(_paymentLink))
            return;

        _uri.OpenUri(_paymentLink);
    }

    private void SelectTab(DonationTerminalTab tab)
    {
        _selectedTab = tab;

        MainContent.Visible = tab == DonationTerminalTab.Main;
        ShopContent.Visible = tab == DonationTerminalTab.Shop;
        SubscriptionsContent.Visible = tab == DonationTerminalTab.Subscriptions;
        InventoryContent.Visible = tab == DonationTerminalTab.Inventory;

        switch (tab)
        {
            case DonationTerminalTab.Main:
                Footer.Text = Loc.GetString("donation-terminal-footer-main");
                break;
            case DonationTerminalTab.Shop:
                Footer.Text = Loc.GetString("donation-terminal-footer-shop");
                break;
            case DonationTerminalTab.Subscriptions:
                Footer.Text = Loc.GetString("donation-terminal-footer-subs");
                break;
            case DonationTerminalTab.Inventory:
                Footer.Text = Loc.GetString("donation-terminal-footer-inventory");
                break;
        }

        SetTabActive(MainTabButton, tab == DonationTerminalTab.Main);
        SetTabActive(ShopTabButton, tab == DonationTerminalTab.Shop);
        SetTabActive(SubscriptionsTabButton, tab == DonationTerminalTab.Subscriptions);
        SetTabActive(InventoryTabButton, tab == DonationTerminalTab.Inventory);
    }

    private static void SetTabActive(Button button, bool active)
    {
        if (active)
            button.AddStyleClass(SunriseStyleClass.StyleClassSciFiTabActive);
        else
            button.RemoveStyleClass(SunriseStyleClass.StyleClassSciFiTabActive);
    }

    private void RefreshPlayerInfo()
    {
        var session = _player.LocalSession;
        if (session == null)
        {
            MainPlayerNameValue.Text = Loc.GetString("donation-terminal-unavailable");
            MainPlayerIdValue.Text = Loc.GetString("donation-terminal-unavailable");
            return;
        }

        MainPlayerNameValue.Text = session.Name;
        MainPlayerIdValue.Text = session.UserId.ToString();
    }

    private void RefreshSponsorInfo()
    {
        if (_sponsorsManager == null)
            return;

        var session = _player.LocalSession;
        if (session == null)
        {
            SetSubscriptionText(Loc.GetString("donation-terminal-unavailable"));
            return;
        }

        if (!_sponsorsManager.ClientIsSponsor())
        {
            SetSubscriptionText(Loc.GetString("donation-terminal-rank-none"));
            return;
        }

        if (!_sponsorsManager.TryGetOocTitle(session.UserId, out var sponsorTitle) ||
            string.IsNullOrWhiteSpace(sponsorTitle))
        {
            SetSubscriptionText(Loc.GetString("donation-terminal-sponsor-active"));
            return;
        }

        var sponsorTier = GetSponsorTier(sponsorTitle);
        SetSubscriptionText(sponsorTier == null
            ? sponsorTitle
            : GetSponsorTierName(sponsorTier));
    }

    private void RefreshSponsorTiers(List<SponsorInfo> sponsorTiers)
    {
        _sponsorTiers.Clear();
        _sponsorTiers.AddRange(sponsorTiers);
        RefreshSponsorInfo();
    }

    private SponsorInfo? GetSponsorTier(string sponsorTitle)
    {
        foreach (var sponsorTier in _sponsorTiers)
        {
            if (string.Equals(sponsorTier.Title, sponsorTitle, StringComparison.OrdinalIgnoreCase))
                return sponsorTier;
        }

        return null;
    }

    private string GetSponsorTierName(SponsorInfo sponsorTier)
    {
        if (string.IsNullOrWhiteSpace(sponsorTier.Title))
            return Loc.GetString("donation-terminal-sponsor-tier", ("tier", sponsorTier.Tier));

        return Loc.GetString(
            "donation-terminal-sponsor-tier-title",
            ("title", sponsorTier.Title),
            ("tier", sponsorTier.Tier));
    }

    private void SetSubscriptionText(string text)
    {
        MainSubscriptionValue.Text = text;
        CurrentSubscriptionValue.Text = text;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _config.UnsubValueChanged(SunriseCCVars.PaymentLink, OnPaymentLinkChanged);

            if (_sponsorsManager != null)
            {
                _sponsorsManager.LoadedSponsorInfo -= RefreshSponsorInfo;
                _sponsorsManager.LoadedSponsorTiers -= RefreshSponsorTiers;
            }
        }

        base.Dispose(disposing);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.Move;

        if (Resizable)
        {
            if (relativeMousePos.Y < DragMarginSize)
            {
                mode = DragMode.Top;
            }
            else if (relativeMousePos.Y > Size.Y - DragMarginSize)
            {
                mode = DragMode.Bottom;
            }

            if (relativeMousePos.X < DragMarginSize)
            {
                mode |= DragMode.Left;
            }
            else if (relativeMousePos.X > Size.X - DragMarginSize)
            {
                mode |= DragMode.Right;
            }
        }

        return mode;
    }

    private enum DonationTerminalTab : byte
    {
        Main,
        Shop,
        Subscriptions,
        Inventory
    }
}
