using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared.AlertLevel;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Communications.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CommunicationsConsoleMenu : FancyWindow
    {
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IGameTiming _timing = default!;
        [Dependency] private ILocalizationManager _loc = default!;
        [Dependency] private IPrototypeManager _protoMan = default!;

        public bool CanAnnounce;
        public bool CanBroadcast;
        public bool CanCall;
        // Sunrise added start - управление ретрансляцией сообщений
        public bool CanRelay;
        public bool IsRelaying;
        public float RelayCooldownRemaining;
        public float RelayTimeRemaining;
        // Sunrise added end
        public bool CountdownStarted;
        public TimeSpan? CountdownEnd;

        public ProtoId<AlertLevelPrototype>? CurrentAlertLevel;
        public List<ProtoId<AlertLevelPrototype>> SelectableAlertLevels = new();
        public bool AlertLevelSelectable;

        public event Action? OnEmergencyLevel;
        public event Action<ProtoId<AlertLevelPrototype>>? OnAlertLevel;
        public event Action<string>? OnAnnounce;
        public event Action<string>? OnBroadcast;
        public event Action? OnToggleRelay; // Sunrise-Edit

        public CommunicationsConsoleMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            MessageInput.Placeholder = new Rope.Leaf(_loc.GetString("comms-console-menu-announcement-placeholder"));

            var maxAnnounceLength = _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);
            MessageInput.OnTextChanged += (args) =>
            {
                if (args.Control.TextLength > maxAnnounceLength)
                {
                    AnnounceButton.Disabled = true;
                    AnnounceButton.ToolTip = Loc.GetString("comms-console-message-too-long");
                }
                else
                {
                    AnnounceButton.Disabled = !CanAnnounce;
                    AnnounceButton.ToolTip = null;

                }
            };

            AnnounceButton.OnPressed += _ => OnAnnounce?.Invoke(Rope.Collapse(MessageInput.TextRope));
            AnnounceButton.Disabled = !CanAnnounce;

            BroadcastButton.OnPressed += _ => OnBroadcast?.Invoke(Rope.Collapse(MessageInput.TextRope));
            BroadcastButton.Disabled = !CanBroadcast;

            // Sunrise-Start
            RelayButton.OnPressed += _ => OnToggleRelay?.Invoke();
            RelayButton.Disabled = !CanRelay;
            // Sunrise-End

            AlertLevelButton.OnItemSelected += args =>
            {
                var metadata = AlertLevelButton.GetItemMetadata(args.Id);
                if (metadata != null && metadata is ProtoId<AlertLevelPrototype> cast)
                {
                    OnAlertLevel?.Invoke(cast);
                }
            };


            AlertLevelButton.Disabled = !AlertLevelSelectable;

            EmergencyShuttleButton.OnPressed += _ => OnEmergencyLevel?.Invoke();
            EmergencyShuttleButton.Disabled = !CanCall;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            UpdateCountdown();
            UpdateRelayUi(); // Sunrise-Edit
            // TODO: Countdown for alert level delay
        }

        public void UpdateAlertLevels()
        {
            AlertLevelButton.Clear();

            if (CurrentAlertLevel == null)
                return;

            if (!AlertLevelSelectable)
            {
                // selection is locked, only show the current alert
                var name = _protoMan.Index(CurrentAlertLevel).LocalizedName;
                AlertLevelButton.AddItem(name);
                AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, CurrentAlertLevel);
            }
            else
            {
                foreach (var alert in SelectableAlertLevels)
                {
                    var name = _protoMan.Index(alert).LocalizedName;
                    AlertLevelButton.AddItem(name);
                    AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, alert);
                    if (alert == CurrentAlertLevel)
                        AlertLevelButton.Select(AlertLevelButton.ItemCount - 1);
                }
            }
        }

        public void UpdateCountdown()
        {
            if (!CountdownStarted)
            {
                CountdownLabel.SetMessage(string.Empty);
                CountdownLabel.Visible = false; // Sunrise-Edit
                EmergencyShuttleButton.Text = Loc.GetString("comms-console-menu-call-shuttle");
                return;
            }

            var diff = MathHelper.Max((CountdownEnd - _timing.CurTime) ?? TimeSpan.Zero, TimeSpan.Zero);

            EmergencyShuttleButton.Text = Loc.GetString("comms-console-menu-recall-shuttle");
            var infoText = Loc.GetString($"comms-console-menu-time-remaining",
                ("time", diff.ToString(@"hh\:mm\:ss", CultureInfo.CurrentCulture)));
            CountdownLabel.SetMessage(infoText);
            CountdownLabel.Visible = true; // Sunrise-Edit
        }

        // Sunrise-Start
        public void UpdateRelayUi()
        {
            RelayButton.Disabled = !CanRelay && !IsRelaying;
            if (IsRelaying)
            {
                RelayButton.Text = Loc.GetString("comms-console-menu-relay-stop");
                var remaining = TimeSpan.FromSeconds(Math.Max(0f, RelayTimeRemaining));
                var text = Loc.GetString("comms-console-menu-relay-time-left", ("time", remaining.ToString(@"mm\:ss", CultureInfo.CurrentCulture)));
                RelayStatusLabel.Visible = true;
                RelayStatusLabel.SetMessage(text);
            }
            else if (RelayCooldownRemaining > 0f)
            {
                var remaining = TimeSpan.FromSeconds(RelayCooldownRemaining);
                RelayButton.Text = Loc.GetString("comms-console-menu-relay-button");
                RelayStatusLabel.SetMessage(Loc.GetString("comms-console-menu-relay-cooldown", ("time", remaining.ToString(@"mm\:ss", CultureInfo.CurrentCulture))));
                RelayStatusLabel.Visible = true;
                RelayButton.Disabled = true;
            }
            else
            {
                RelayButton.Text = Loc.GetString("comms-console-menu-relay-button");
                RelayStatusLabel.Visible = false;
                RelayStatusLabel.SetMessage(string.Empty);
            }
        }
        // Sunrise-End
    }
}
