// © SUNRISE, An EULA/CLA with a hosting restriction, full text: https://github.com/space-sunrise/space-station-14/blob/master/CLA.txt
using System.Linq;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Sunrise.Interfaces.Shared;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.StylesheetHelpers;

namespace Content.Client._Sunrise.SponsorTiers;

[GenerateTypedNameReferences]
public sealed partial class SponsorTiers : Control
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private readonly ISharedSponsorsManager? _sponsorsManager;
    private readonly Dictionary<int, int> _tierTabs = new();

    private int? _pendingSponsorTier;

    public SponsorTiers()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        IoCManager.Instance!.TryResolveType(out _sponsorsManager);
        if (_sponsorsManager == null)
            return;

        _sponsorsManager.LoadedSponsorTiers += ReloadSponsorTiers;

        ReloadSponsorTiers(_sponsorsManager.GetSponsorTiers());
    }

    private void ReloadSponsorTiers(List<SponsorInfo> sponsorTiers)
    {
        if (Disposed)
            return;

        _tierTabs.Clear();
        SponsorTiersContainer.RemoveAllChildren();
        for (var i = 0; i < sponsorTiers.Count; i++)
        {
            var sponsorTier = sponsorTiers[i];
            var entry = new SponsorTierEntry(sponsorTier, i);
            _tierTabs[sponsorTier.Tier] = i;
            SponsorTiersContainer.AddChild(entry);
            SponsorTiersContainer.SetTabTitle(i, sponsorTier.Title ?? "No Title");
            var stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNano;
            var notoSans20 = _resourceCache.GetFont(
                [
                    "/Fonts/NotoSans/NotoSans-Regular.ttf",
                    "/Fonts/NotoSans/NotoSansSymbols-Regular.ttf",
                    "/Fonts/NotoSans/NotoSansSymbols2-Regular.ttf",
                ],
                20
            );
            var rules = stylesheet.Rules.ToList();
            var tabContainerFontRule = new StyleRule(
                Element<TabContainer>(),
                new[] { new StyleProperty("font", notoSans20) }
            );

            rules.Add(tabContainerFontRule);

            stylesheet = new Stylesheet(rules.ToArray());
            SponsorTiersContainer.Stylesheet = stylesheet;
        }

        if (_pendingSponsorTier != null && TrySelectSponsorTier(_pendingSponsorTier.Value))
            _pendingSponsorTier = null;
    }

    public void SelectSponsorTier(int sponsorTier)
    {
        if (TrySelectSponsorTier(sponsorTier))
        {
            _pendingSponsorTier = null;
            return;
        }

        _pendingSponsorTier = sponsorTier;
    }

    private bool TrySelectSponsorTier(int sponsorTier)
    {
        if (!_tierTabs.TryGetValue(sponsorTier, out var tab) ||
            tab < 0 ||
            tab >= SponsorTiersContainer.ChildCount)
        {
            return false;
        }

        SponsorTiersContainer.CurrentTab = tab;
        return true;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing && _sponsorsManager != null)
        {
            _sponsorsManager.LoadedSponsorTiers -= ReloadSponsorTiers;
        }
    }
}
