using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.GameTicking.Managers;
using Content.Client.Resources;
using Content.Shared._Sunrise.Roadmap;
using Content.Shared._Sunrise.SunriseCCVars;
using Content.Shared._Sunrise.Tutorial.Prototypes;
using Content.Shared.Anomaly;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.Tutorial;

[GenerateTypedNameReferences]
public sealed partial class TutorialWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IEntitySystemManager _entSys = default!;
    public Action<TutorialSequencePrototype>? OnTutorialButtonPressed;
    private readonly ClientGameTicker _gameTicker;
    private TutorialCategoryButton? _selectedCategory;
    private readonly HashSet<string> _completedTutorials = new();

    public TutorialWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _gameTicker = _entSys.GetEntitySystem<ClientGameTicker>();

        _gameTicker.LobbyStatusUpdated += UpdateRoundState;
        GenerateCategories();
    }

    private void GenerateCategories()
    {
        var categories = _prototype.EnumeratePrototypes<TutorialCategoryPrototype>().ToList();

        foreach (var category in categories)
        {
            var button = new TutorialCategoryButton(category, OnCategorySelected);
            CategoryContainer.AddChild(button);
        }

        // Select the first category by default
        if (CategoryContainer.Children.FirstOrDefault() is TutorialCategoryButton firstCategory)
        {
            OnCategorySelected(firstCategory);
        }
    }

    private void OnCategorySelected(TutorialCategoryButton categoryButton)
    {
        // Deselect previous category
        if (_selectedCategory != null)
        {
            _selectedCategory.SetSelected(false);
        }

        _selectedCategory = categoryButton;
        _selectedCategory.SetSelected(true);

        RebuildButtonsForCategory(_selectedCategory.Category);
    }

    private void PopulateButtonsForCategory(TutorialCategoryPrototype category)
    {
        var roundNotStarted = !_gameTicker.IsGameStarted;
        var deniedText = Loc.GetString("round-is-not-ready");

        foreach (var protoId in category.Tutorials)
        {
            if (!_prototype.TryIndex(protoId, out var proto))
                continue;

            var sb = new StringBuilder();

            sb.AppendLine(proto.Tooltip);

            sb.AppendLine(Loc.GetString("tutorial-time", ("time", proto.Duration.ToString("mm\\:ss"))));

            var status = deniedText;

            if (!roundNotStarted)
            {
                var completed = _completedTutorials.Contains(proto.ID);
                status = completed ? Loc.GetString("tutorial-completed") : Loc.GetString("tutorial-is-not-completed");
            }

            sb.AppendLine(Loc.GetString("tutorial-status", ("status", status)));


            var texture = _resourceCache.GetResource<TextureResource>(proto.Texture);
            var config = new FancyCardConfig
            {
                TitleText = proto.Name,
                DescText = sb.ToString(),
                BackdropTexture = texture,
                Size = new Vector2(570, 350)
            };

            var entry = new FancyCard(config);
            entry.ActionPressed += () => OnTutorialButtonPressed?.Invoke(proto);
            entry.SetDenied(roundNotStarted, deniedText);

            ButtonGrid.AddChild(entry);
        }
    }

    public void SetCompletedTutorials(IEnumerable<string> completedTutorials)
    {
        _completedTutorials.Clear();
        _completedTutorials.UnionWith(completedTutorials);

        if (_selectedCategory != null)
            RebuildButtonsForCategory(_selectedCategory.Category);
    }
    private void RebuildButtonsForCategory(TutorialCategoryPrototype category)
    {
        ButtonGrid.Children.Clear();
        PopulateButtonsForCategory(category);
    }
    private void UpdateRoundState()
    {
        if (_selectedCategory != null)
            RebuildButtonsForCategory(_selectedCategory.Category);
    }
}
