using System;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Sunrise.Tutorial;

[GenerateTypedNameReferences]
public sealed partial class TutorialProgressBar : PanelContainer
{
    public TutorialProgressBar()
    {
    }

    public void SetLabel(string text)
    {
        ProgressText.Text = text;
    }

    public void SetProgress(float value)
    {
        Progress.Value = value;
    }

    public void SetControlWidth(float width)
    {
        var clamped = MathF.Max(width, 120f);
        MinSize = new Vector2(clamped, 0f);
        Progress.MinSize = new Vector2(clamped, Progress.MinSize.Y);
    }
}
