using System.Numerics;
using Content.Client.Resources;
using Content.Shared._Sunrise.Roadmap;
using Content.Shared._Sunrise.SunriseCCVars;
using Content.Shared._Sunrise.Tutorial.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.Tutorial;

[GenerateTypedNameReferences]
public sealed partial class TutorialWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    public Action<TutorialSequencePrototype>? OnTutorialButtonPressed;
    private readonly Dictionary<string, TutorialButtonEntry> _buttons = new();

    public TutorialWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        PopulateButtons();
    }

    private void PopulateButtons()
    {
        foreach (var proto in _prototype.EnumeratePrototypes<TutorialSequencePrototype>())
        {
            var texture = _resourceCache.GetResource<TextureResource>(proto.Texture);
            AddButton(proto.Name, texture, OnTutorialButtonPressed, proto, proto.Tooltip);
        }
    }
    public TextureButton AddButton(
        string name,
        Texture texture,
        Action<TutorialSequencePrototype>? onPressed,
        TutorialSequencePrototype proto,
        string? tooltip = null)
    {
        var button = new TextureButton
        {
            TextureNormal = texture,
            StyleClasses = { "ButtonSquare" },
            ToolTip = tooltip,
            MinSize = new Vector2(100, 100)
        };

        var title = new Label
        {
            Text = Loc.GetString(name),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Align = Label.AlignMode.Center,
            FontColorOverride = Color.White,
            Visible = false
        };

        var denied = new Label
        {
            Text = Loc.GetString("round-is-not-ready"),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Align = Label.AlignMode.Center,
            FontColorOverride = Color.Red,
            Visible = false
        };

        button.OnMouseEntered += _ =>
        {
            button.Modulate = new Color(0.7f, 0.7f, 0.7f);
            title.Visible = true;
        };

        button.OnMouseExited += _ =>
        {
            button.Modulate = Color.White;
            title.Visible = false;
        };
        button.OnPressed += _ => onPressed?.Invoke(proto);

        button.AddChild(denied);
        button.AddChild(title);
        ButtonGrid.AddChild(button);

        return button;
    }

    private sealed class TutorialButtonEntry
    {
        public TextureButton? Button;
        public Label? Title;
        public Label? Denied;
        public TutorialSequencePrototype? Proto;
    }
}
