using Content.Shared._Sunrise.Tutorial.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Sunrise.Tutorial;

[GenerateTypedNameReferences]
public sealed partial class TutorialEntry : BoxContainer
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    public TutorialEntry(TutorialSequencePrototype proto,
        Action<TutorialSequencePrototype>? onPressed)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var texture = _resourceCache.GetResource<TextureResource>(proto.Texture);

        Title.Text = proto.Name;
        TutorialButton.ToolTip = proto.Tooltip;
        TutorialButton.TextureNormal = texture;

        TutorialButton.OnPressed += _ => onPressed?.Invoke(proto);
    }

    public void SetDenied(bool denied, string? reason = null)
    {
        TutorialButton.Disabled = denied;
        Denied.Visible = denied;

        if (reason != null)
            Denied.Text = reason;

        SetMouseHover(!denied);

        Title.Visible = false;

        TutorialButton.Modulate = denied
            ? new Color(255, 197, 197)
            : Color.White;
    }

    private void SetMouseHover(bool enabled)
    {
        if (!enabled)
            return;

        TutorialButton.OnMouseEntered += _ =>
        {
            TutorialButton.Modulate = new Color(0.7f, 0.7f, 0.7f);
            Title.Visible = true;
        };

        TutorialButton.OnMouseExited += _ =>
        {
            TutorialButton.Modulate = Color.White;
            Title.Visible = false;
        };
    }
}
