using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client._Sunrise.PlayerCache;
using Content.Client.Lobby.UI.Loadouts;
using Content.Shared._Sunrise.Pets;
using Content.Shared._Sunrise.SponsorInventory;
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Sunrise.Interfaces.Shared;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.SponsorInventory;

[GenerateTypedNameReferences]
public sealed partial class SunriseInventoryWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly PlayerCacheManager _playerCache = default!;

    private static readonly string[] InventorySlots =
    [
        "head",
        "mask",
        "eyes",
        "ears",
        "jumpsuit",
        "outerClothing",
        "gloves",
        "shoes",
        "back",
        "belt",
        "id",
        "neck",
        "pocket1",
        "pocket2",
        "suitstorage",
    ];

    private readonly List<string?> _jobOptions = new();

    private ISharedSponsorsManager? _sponsors;
    private HumanoidCharacterProfile? _profile;
    private SunriseInventoryProfile _sponsorInventory = new();
    private int? _slot;
    private int _selectedJobOption;
    private SunriseInventoryTab _selectedTab = SunriseInventoryTab.Loadout;

    public event Action<HumanoidCharacterProfile, int, SunriseInventoryProfile>? OnSaveRequested;
    public event Action<string?>? OnPetSelected;

    public SunriseInventoryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        IoCManager.Instance!.TryResolveType(out _sponsors);

        JobOption.OnItemSelected += args =>
        {
            JobOption.SelectId(args.Id);
            _selectedJobOption = args.Id;
            RefreshSelectedTab();
        };

        SaveButton.OnPressed += _ =>
        {
            if (_profile != null && _slot != null)
                OnSaveRequested?.Invoke(_profile.Clone(), _slot.Value, _sponsorInventory.Clone());
        };

        LoadoutTabButton.OnPressed += _ => SelectTab(SunriseInventoryTab.Loadout);
        SponsorTabButton.OnPressed += _ => SelectTab(SunriseInventoryTab.Sponsor);
        PetsTabButton.OnPressed += _ => SelectTab(SunriseInventoryTab.Pets);

        _playerCache.CacheChanged += RefreshPets;

        if (_sponsors != null)
            _sponsors.LoadedSponsorInventoryConfig += OnSponsorInventoryConfigLoaded;
    }

    public void SetProfile(HumanoidCharacterProfile? profile, int? slot, SunriseInventoryProfile? sponsorInventory)
    {
        var previousJob = CurrentJobId;

        _profile = profile?.Clone();
        _sponsorInventory = sponsorInventory?.Clone() ?? new SunriseInventoryProfile();
        _slot = slot;
        SaveButton.Disabled = _profile == null || _slot == null;
        ProfileName.Text = _profile?.Name ?? Loc.GetString("sunrise-inventory-no-profile");

        BuildJobOptions(previousJob);
        RefreshSelectedTab();
    }

    public void RefreshPets()
    {
        PetsList.RemoveAllChildren();

        var currentPet = _playerCache.TryGetCachedPet(out var cachedPet) ? cachedPet : null;
        var localSession = _player.LocalSession;
        var availablePets = GetAvailablePets(localSession);

        var clearButton = new Button
        {
            Text = Loc.GetString("sunrise-inventory-pets-clear"),
            ToggleMode = true,
            Pressed = string.IsNullOrEmpty(currentPet),
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5),
        };
        clearButton.OnPressed += _ => OnPetSelected?.Invoke(null);
        PetsList.AddChild(clearButton);

        foreach (var pet in _prototype.EnumeratePrototypes<PetSelectionPrototype>()
                     .OrderBy(p => p.LocalizedName))
        {
            var isAvailable = !pet.SponsorOnly || availablePets.Contains(pet.ID);
            var button = new Button
            {
                Text = pet.LocalizedName,
                ToggleMode = true,
                Pressed = pet.ID == currentPet,
                Disabled = !isAvailable,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 5),
            };

            button.OnPressed += _ =>
            {
                if (isAvailable)
                    OnPetSelected?.Invoke(pet.ID);
            };

            PetsList.AddChild(button);
        }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _playerCache.CacheChanged -= RefreshPets;

            if (_sponsors != null)
                _sponsors.LoadedSponsorInventoryConfig -= OnSponsorInventoryConfigLoaded;
        }

        base.Dispose(disposing);
    }

    private void OnSponsorInventoryConfigLoaded(SponsorInventoryConfig config)
    {
        RefreshSponsorInventory();
    }

    private void SelectTab(SunriseInventoryTab tab)
    {
        _selectedTab = tab;

        LoadoutContent.Visible = tab == SunriseInventoryTab.Loadout;
        SponsorContent.Visible = tab == SunriseInventoryTab.Sponsor;
        PetsContent.Visible = tab == SunriseInventoryTab.Pets;

        RefreshSelectedTab();
    }

    private void RefreshSelectedTab()
    {
        switch (_selectedTab)
        {
            case SunriseInventoryTab.Loadout:
                RefreshLoadouts();
                break;
            case SunriseInventoryTab.Sponsor:
                RefreshSponsorInventory();
                break;
            case SunriseInventoryTab.Pets:
                RefreshPets();
                break;
        }
    }

    private void BuildJobOptions(string? previousJob)
    {
        JobOption.Clear();
        _jobOptions.Clear();

        AddJobOption(Loc.GetString("sunrise-inventory-job-all"), null);

        foreach (var job in _prototype.EnumeratePrototypes<JobPrototype>()
                     .Where(j => j.SetPreference)
                     .OrderBy(j => j.LocalizedName))
        {
            AddJobOption(job.LocalizedName, job.ID);
        }

        _selectedJobOption = Math.Max(0, _jobOptions.IndexOf(previousJob));
        JobOption.SelectId(_selectedJobOption);
    }

    private void AddJobOption(string text, string? jobId)
    {
        var id = _jobOptions.Count;
        _jobOptions.Add(jobId);
        JobOption.AddItem(text, id);
    }

    private string? CurrentJobId
    {
        get
        {
            if (_selectedJobOption < 0 || _selectedJobOption >= _jobOptions.Count)
                return null;

            return _jobOptions[_selectedJobOption];
        }
    }

    private void RefreshLoadouts()
    {
        LoadoutList.RemoveAllChildren();

        if (_profile == null)
        {
            AddInfo(LoadoutList, "sunrise-inventory-no-profile");
            return;
        }

        var jobId = CurrentJobId;
        if (jobId == null)
        {
            AddInfo(LoadoutList, "sunrise-inventory-loadout-select-job");
            return;
        }

        var jobLoadoutId = LoadoutSystem.GetJobPrototype(jobId);
        var effectiveJobLoadoutId = LoadoutSystem.GetEffectiveRolePrototype(jobLoadoutId, _prototype);

        if (!_prototype.TryIndex<RoleLoadoutPrototype>(effectiveJobLoadoutId, out var roleLoadoutProto))
        {
            AddInfo(LoadoutList, "sunrise-inventory-loadout-missing");
            return;
        }

        var roleLoadout = GetRoleLoadout(jobLoadoutId);
        var loadoutSystem = _entManager.System<LoadoutSystem>();
        var collection = IoCManager.Instance!;
        var sponsorPrototypes = _sponsors?.GetClientPrototypes().ToArray() ?? [];

        roleLoadout.SetDefault(_profile, _player.LocalSession, _prototype, sponsorPrototypes);
        _profile = _profile.WithLoadout(roleLoadout);

        foreach (var groupId in roleLoadoutProto.Groups)
        {
            if (!_prototype.TryIndex(groupId, out LoadoutGroupPrototype? group) || group.Hidden)
                continue;

            LoadoutList.AddChild(new Label
            {
                Text = Loc.GetString(group.Name),
                StyleClasses = { "LabelHeading" },
                Margin = new Thickness(0, 4, 0, 4),
            });

            if (!roleLoadout.SelectedLoadouts.ContainsKey(group.ID))
                roleLoadout.SelectedLoadouts[group.ID] = new List<Loadout>();

            foreach (var loadoutId in group.Loadouts)
            {
                if (!_prototype.TryIndex(loadoutId, out LoadoutPrototype? loadout))
                    continue;

                var selected = roleLoadout.SelectedLoadouts[group.ID].Any(l => l.Prototype == loadout.ID);
                var enabled = roleLoadout.IsValid(
                    _profile,
                    _player.LocalSession,
                    loadout.ID,
                    collection,
                    sponsorPrototypes,
                    out var reason);

                var container = new LoadoutContainer(loadout.ID, !enabled, reason)
                {
                    Text = loadoutSystem.GetName(loadout),
                };
                container.Select.Pressed = selected;
                container.Select.OnPressed += _ => ToggleLoadout(roleLoadout, group.ID, loadout.ID, container.Select.Pressed);

                LoadoutList.AddChild(container);
            }
        }
    }

    private RoleLoadout GetRoleLoadout(string jobLoadoutId)
    {
        if (_profile != null && _profile.Loadouts.TryGetValue(jobLoadoutId, out var existing))
            return existing.Clone();

        return new RoleLoadout(jobLoadoutId);
    }

    private void ToggleLoadout(RoleLoadout roleLoadout, string groupId, string loadoutId, bool pressed)
    {
        if (_profile == null)
            return;

        if (pressed)
            roleLoadout.AddLoadout(groupId, loadoutId, _prototype);
        else
            roleLoadout.RemoveLoadout(groupId, loadoutId, _prototype);

        _profile = _profile.WithLoadout(roleLoadout);
        RefreshLoadouts();
    }

    private void RefreshSponsorInventory()
    {
        SponsorCatalog.RemoveAllChildren();
        SponsorSelection.RemoveAllChildren();

        if (_profile == null)
        {
            AddInfo(SponsorCatalog, "sunrise-inventory-no-profile");
            return;
        }

        if (_sponsors == null || _player.LocalSession == null)
        {
            AddInfo(SponsorCatalog, "sunrise-inventory-sponsor-unavailable");
            return;
        }

        var selection = GetSponsorSelectionSnapshot();
        AddSponsorSelectionSummary(selection);

        var config = _sponsors.GetSponsorInventoryConfig();
        if (config.Items.Length == 0)
        {
            AddInfo(SponsorCatalog, "sunrise-inventory-sponsor-empty");
            return;
        }

        foreach (var item in config.Items
                     .Where(i => !string.IsNullOrWhiteSpace(i.Id))
                     .OrderBy(GetSponsorItemName))
        {
            AddSponsorItemRow(item, selection);
        }
    }

    private SunriseInventorySelection GetSponsorSelectionSnapshot()
    {
        if (_profile == null)
            return new SunriseInventorySelection();

        var jobId = CurrentJobId;
        if (jobId == null)
            return _sponsorInventory.Global.Clone();

        return _sponsorInventory.Jobs.TryGetValue(jobId, out var selection)
            ? selection.Clone()
            : new SunriseInventorySelection();
    }

    private void AddSponsorSelectionSummary(SunriseInventorySelection selection)
    {
        SponsorSelection.AddChild(new Label
        {
            Text = Loc.GetString("sunrise-inventory-current-selection"),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 0, 0, 6),
        });

        if (selection.IsEmpty())
        {
            AddInfo(SponsorSelection, "sunrise-inventory-selection-empty");
            return;
        }

        foreach (var (slot, itemId) in selection.SlotItems)
        {
            SponsorSelection.AddChild(new Label
            {
                Text = Loc.GetString(
                    "sunrise-inventory-selection-slot",
                    ("slot", GetSlotLabel(slot)),
                    ("item", GetSponsorItemName(itemId))),
            });
        }

        foreach (var itemId in selection.BagItems)
        {
            SponsorSelection.AddChild(new Label
            {
                Text = Loc.GetString("sunrise-inventory-selection-bag", ("item", GetSponsorItemName(itemId))),
            });
        }
    }

    private void AddSponsorItemRow(SponsorInventoryItemInfo item, SunriseInventorySelection selection)
    {
        var selected = IsSponsorItemSelected(selection, item.Id);
        var canUse = _player.LocalSession != null &&
                     SunriseInventoryValidation.CanUseItem(
                         item.Id,
                         CurrentJobId,
                         _player.LocalSession,
                         _prototype,
                         _sponsors);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
            Margin = new Thickness(0, 0, 0, 5),
        };

        row.AddChild(new Label
        {
            Text = GetSponsorItemName(item),
            ClipText = true,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });

        var slotOption = new OptionButton
        {
            MinWidth = 170,
        };
        slotOption.AddItem(Loc.GetString("sunrise-inventory-slot-bag"), 0);

        for (var i = 0; i < InventorySlots.Length; i++)
        {
            slotOption.AddItem(GetSlotLabel(InventorySlots[i]), i + 1);
        }

        slotOption.SelectId(0);
        row.AddChild(slotOption);

        var action = new Button
        {
            Text = Loc.GetString(selected ? "sunrise-inventory-remove" : "sunrise-inventory-add"),
            Disabled = !selected && !canUse,
            MinWidth = 100,
        };

        action.OnPressed += _ =>
        {
            if (selected)
                RemoveSponsorItem(item.Id);
            else
                AddSponsorItem(item.Id, slotOption.SelectedId);
        };

        row.AddChild(action);
        SponsorCatalog.AddChild(row);
    }

    private void AddSponsorItem(string itemId, int optionId)
    {
        UpdateSponsorSelection(selection =>
        {
            RemoveSponsorItem(selection, itemId);

            if (optionId <= 0)
            {
                selection.BagItems.Add(itemId);
                return;
            }

            var slotIndex = optionId - 1;
            if (slotIndex >= 0 && slotIndex < InventorySlots.Length)
                selection.SlotItems[InventorySlots[slotIndex]] = itemId;
        });
    }

    private void RemoveSponsorItem(string itemId)
    {
        UpdateSponsorSelection(selection => RemoveSponsorItem(selection, itemId));
    }

    private void UpdateSponsorSelection(Action<SunriseInventorySelection> update)
    {
        if (_profile == null)
            return;

        var inventory = _sponsorInventory.Clone();
        var jobId = CurrentJobId;
        var selection = jobId == null
            ? inventory.Global
            : inventory.Jobs.GetValueOrDefault(jobId)?.Clone() ?? new SunriseInventorySelection();

        update(selection);

        if (jobId == null)
        {
            inventory.Global = selection;
        }
        else if (selection.IsEmpty())
        {
            inventory.Jobs.Remove(jobId);
        }
        else
        {
            inventory.Jobs[jobId] = selection;
        }

        _sponsorInventory = inventory;
        RefreshSponsorInventory();
    }

    private static void RemoveSponsorItem(SunriseInventorySelection selection, string itemId)
    {
        foreach (var slot in selection.SlotItems.Where(p => p.Value == itemId).Select(p => p.Key).ToArray())
        {
            selection.SlotItems.Remove(slot);
        }

        selection.BagItems.RemoveAll(i => i == itemId);
    }

    private static bool IsSponsorItemSelected(SunriseInventorySelection selection, string itemId)
    {
        return selection.BagItems.Contains(itemId) || selection.SlotItems.ContainsValue(itemId);
    }

    private HashSet<string> GetAvailablePets(ICommonSession? localSession)
    {
        if (localSession != null &&
            _sponsors != null &&
            _sponsors.TryGetPets(localSession.UserId, out var availablePets) &&
            availablePets != null)
        {
            return availablePets.ToHashSet();
        }

        return new HashSet<string>();
    }

    private string GetSponsorItemName(SponsorInventoryItemInfo item)
    {
        return GetEntityName(item.EntityPrototype, item.Id);
    }

    private string GetSponsorItemName(string itemId)
    {
        if (_sponsors == null)
            return itemId;

        foreach (var item in _sponsors.GetSponsorInventoryConfig().Items)
        {
            if (item.Id == itemId)
                return GetSponsorItemName(item);
        }

        return itemId;
    }

    private string GetEntityName(string entityPrototype, string fallback)
    {
        return _prototype.TryIndex<EntityPrototype>(entityPrototype, out var prototype)
            ? prototype.Name
            : fallback;
    }

    private static string GetSlotLabel(string slot)
    {
        var suffix = slot switch
        {
            "outerClothing" => "outer-clothing",
            "pocket1" => "pocket-1",
            "pocket2" => "pocket-2",
            _ => slot,
        };

        return Loc.GetString($"sunrise-inventory-slot-{suffix}");
    }

    private static void AddInfo(BoxContainer container, string locId)
    {
        container.AddChild(new Label
        {
            Text = Loc.GetString(locId),
            StyleClasses = { "LabelSubText" },
        });
    }

    private enum SunriseInventoryTab : byte
    {
        Loadout,
        Sponsor,
        Pets,
    }
}
