using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.PirateSale.UI;

[GenerateTypedNameReferences]
public sealed partial class PiratePalletMenu : FancyWindow
{
    public Action? SellRequested;
    public Action? AppraiseRequested;

    public PiratePalletMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
        AppraiseButton.OnPressed += OnAppraisePressed;
    }

    public void SetAppraisalCredits(int amount)
    {
        AppraisalLabel.Text = Loc.GetString("pirate-pallet-menu-credits-amount", ("amount", amount.ToString()));
    }

    public void SetDoubloons(int amount)
    {
        DoubloonsLabel.Text = Loc.GetString("pirate-pallet-menu-doubloons-amount", ("amount", amount.ToString()));
    }

    public void SetCount(int count)
    {
        CountLabel.Text = count.ToString();
    }

    public void SetEnabled(bool enabled)
    {
        AppraiseButton.Disabled = !enabled;
        SellButton.Disabled = !enabled;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs _)
    {
        SellRequested?.Invoke();
    }

    private void OnAppraisePressed(BaseButton.ButtonEventArgs _)
    {
        AppraiseRequested?.Invoke();
    }
}
