using System;
using System.Numerics;
using Robust.Client.Graphics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Text;

namespace Content.Client._Sunrise.FancyCardControl;

[GenerateTypedNameReferences]
public sealed partial class FancyCard : Control
{
    private string _descText = string.Empty;

    public event Action? ActionPressed;

    public FancyCard(FancyCardConfig config)
    {
        RobustXamlLoader.Load(this);
        ApplyConfig(config);

        ActionButton.OnPressed += _ => ActionPressed?.Invoke();
    }

    public void ApplyConfig(FancyCardConfig config)
    {
        TitleLabel.Text = config.TitleText;

        _descText = config.DescText;
        DescLabel.Text = string.IsNullOrEmpty(_descText) ? "-" : _descText;
        DescOuter.Visible = config.ShowDescription;

        ActionButton.Text = config.ActionText;
        ActionButton.ToolTip = config.ActionTooltip;
        ActionPanel.Visible = config.ShowAction;

        Backdrop.Texture = config.BackdropTexture;

        if (config.Size != null)
            SetSize = config.Size.Value;
    }

    public void SetDenied(bool denied, string? reason = null)
    {
        ActionButton.Disabled = denied;
    }
}

public sealed record FancyCardConfig
{
    public string TitleText { get; init; } = string.Empty;
    public string DescText { get; init; } = string.Empty;
    public string ActionText { get; init; } = Loc.GetString("fancy-card-default");
    public string? ActionTooltip { get; init; }
    public Texture? BackdropTexture { get; init; }
    public Vector2? Size { get; init; }
    public bool ShowAction { get; init; } = true;
    public bool ShowDescription { get; init; } = true;
}
