using Content.Shared._Sunrise.Roadmap;
using Content.Shared._Sunrise.SunriseCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class Roadmap : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public Roadmap()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var roadmapId = _cfg.GetCVar(SunriseCCVars.RoadmapId);
        if (!_prototype.TryIndex<RoadmapVersionsPrototype>(roadmapId, out var roadmapVersions))
            return;

        PopulateRoadmap(roadmapVersions);
    }

    private void PopulateRoadmap(RoadmapVersionsPrototype roadmapVersions)
    {
        Title = $"{_loc.GetString("ui-roadmap-header")} {roadmapVersions.Fork}";

        MainBox.RemoveAllChildren();

        foreach (var data in roadmapVersions.Versions)
        {
            var (card, itemsBox) = CreateVersionCard(data.Name);
            GenerateGoals(data.Goals, itemsBox);
            MainBox.AddChild(card);
        }
    }

    private (PanelContainer card, BoxContainer itemsBox) CreateVersionCard(string labelName)
    {
        var card = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = false,
            Margin = new Thickness(5),
        };

        var cardStyle = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#121111"),
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8,
        };
        card.PanelOverride = cardStyle;

        var outerBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        card.AddChild(outerBox);

        var header = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 8),
        };
        var headerStyle = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#2a2929"),
            ContentMarginLeftOverride = 8,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
            ContentMarginRightOverride = 8,
        };
        header.PanelOverride = headerStyle;

        var nameLabel = new Label
        {
            Text = _loc.GetString(labelName),
            StyleClasses = { "LabelHeadingBigger" },
            HorizontalAlignment = HAlignment.Center,
            HorizontalExpand = true,
            FontColorOverride = Color.FromHex("#ffffff"),
        };
        header.AddChild(nameLabel);
        outerBox.AddChild(header);

        var itemsBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        outerBox.AddChild(itemsBox);

        return (card, itemsBox);
    }

    private void GenerateGoals(IReadOnlyList<RoadmapGoal> goals, BoxContainer targetBox)
    {
        foreach (var goal in goals)
        {
            var roadmapItem = new RoadmapItem
            {
                HeaderText = _loc.GetString(goal.Name),
                Text = _loc.GetString(goal.Desc),
                ItemState = goal.State,
            };

            targetBox.AddChild(roadmapItem);
        }
    }
}
