using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyProfileWindow : DefaultWindow
{
    public LobbyProfileWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Opened()
    {
        base.Opened();

        UserProfileBody.RequestAccountBindingsRefresh();
    }
}
